#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const fetch = require("node-fetch");

const config = require("../../../genesis.config");

console.log("Starting");
