#!/usr/bin/env node

const fs = require("fs-extra");
const config = require("../../../brs.config");
if (!fs.existsSync(config.scaffold.destination) ) {
    fs.mkdirSync(config.scaffold.destination);}

require("./brs-generate-genesis-components");
require("./brs-generate-genesis-html2react");
require("./brs-generate-genesis-tests");
require("./brs-generate-genesis-ts");
