#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const fetch = require("node-fetch");

const config = require("../../../genesis.config");

require('./brs-generate-genesis-components')
require('./brs-generate-genesis-html2react')
require('./brs-generate-genesis-tests')
require('./brs-generate-genesis-ts')
 