#!/usr/bin/env node

console.log("TESTINGt");

const fs = require("fs");
const path = require("path");

const fetch = require("node-fetch");

const config = require("../../genesis.config");

console.log("config", config);
