#!/usr/bin/env node

console.log(
'Usage:  npm run brs-git-pull-wp'
);
console.log("This script only does a git pull on the WordPress on all custom brs plugins/themes.")
require('dotenv-flow').config();

const fs = require('fs');

const dotenv = require('dotenv');
const fetch = require('node-fetch');

const config = require('../genesis.config');
const envConfig = dotenv.parse(fs.readFileSync('.env.local'));
for (const k in envConfig) {
	process.env[k] = envConfig[k];
}

const main = async () => {
	const body = JSON.stringify({
	query: `
	query { brsUpdateWp(key: "${process.env.FAUSTWP_SECRET_KEY}") }`,
	});

	fetch(config.endpoint, {
		method: 'POST',
		headers: {
		'Content-Type': 'application/json',
		},
		body: body,
	})
	.then((res) => res.json())
	.then((result) => {
		console.log("Result", result)
	});
};

main();

		  
				  