#!/usr/bin/env node
/**
 * Generates the tw.generate.js
* https://blog.dennisokeeffe.com/blog/2020-07-26-using-tailwind-theme-anywhere
*
*/
const fs = require('fs');
const path = require('path');

const prettier = require('prettier');
const resolveConfig = require('tailwindcss/resolveConfig');

// bring in the Tailwind config
const tailwindConfig = require('../tailwind.config.js');

const { theme } = resolveConfig(tailwindConfig);
const themeStr = JSON.stringify(theme);
const js = `
const theme  = ${themeStr}

export default theme
`;

try {
// write the file to src/styles/tw.generate.js after
// having prettier format the string for us
fs.writeFileSync(
	path.resolve(process.cwd(), './src/styles/tw.generate.js'),
	prettier.format(js, { parser: 'babel' }),
	'utf-8'
);
} catch (err) {
// uh-oh, something happened here!
console.log(err.message);
}
				  